### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by finallight1** [rdbo/ImGui-DirectX-9-Kiero-Hook#2]
When injected, the window shows but it doesnt resize and the buttons, checkboxes and everything doesnt work, i can even move the window

**Comment by TrotzeyOnPC** [comment]
hah suks to be u

**Comment by rdbo** [comment]
Oh, I received a notification from this last comment an it just poped in my mind why it could not be working. Some games need a different implementation for the DX9 Hook, other than this one. It hapened on Tibia, where the Window would be drawn on multiple screens and would be nonfuncional. I don't remember how to fix it for these specific games, but I remember it had something to do with viewports. You may find something about that on GuidedHacking, search for Tibia posts. If it's not the same problem, then I have no clue
