### ISSUE TITLE
Tons of errors on freshly opening the .vcxproj file

### ISSUE THREAD

**Issue by lambits** [rdbo/ImGui-DirectX-9-Kiero-Hook#3]
This is what happens if I open main.cpp
![xdghj](https://user-images.githubusercontent.com/48295237/95115214-c8f04d80-074d-11eb-8e94-428be79e07b0.PNG)
I have no clue to why it happens
I use Visual Studio 2017

**Comment by rdbo** [comment]
I never open a project through a .vcxproj file, have you tried using the .sln file?
Also, I used VS 2019 when I made this, but I don't think that's an issue

**Comment by lambits** [comment]
> I never open a project through a .vcxproj file, have you tried using the .sln file?
> Also, I used VS 2019 when I made this, but I don't think that's an issue

Same when opening the .sln file. 

List of errors:
It's really big. If I pasted it, it wouldn't let me post the comment on GitHub because it is too long.
https://pastebin.com/SgeimJCp

**Comment by lambits** [comment]
I'll try maybe using a different IDE and compiler and see if that works

**Comment by lambits** [comment]
https://pastebin.com/4yLKT9Sb
Nope. Less errors, but I only get "No such file or directory"

**Comment by rdbo** [comment]
Do you have the DirectX and Windows SDK installed?
https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/
https://www.microsoft.com/en-us/download/details.aspx?id=6812

**Comment by lambits** [comment]
> Do you have the DirectX and Windows SDK installed?
> https://developer.microsoft.com/en-US/windows/downloads/windows-10-sdk/
> https://www.microsoft.com/en-us/download/details.aspx?id=6812

Yes

**Comment by rdbo** [comment]
It seems Visual Studio is not being able to include Windows SDK headers, DirectX headers and even some C standard headers, like stdlib.h. I think your Visual Studio settings might be screwed, possibly it wasn't installed properly.
I'd try:
Manually setting all the include paths for Windows SDK, DirectX SDK and Visual Studio's Default Include Path.
Resetting Visual Studio settings
Reinstalling Visual Studio
