### ISSUE TITLE
Unreferenced external symbol bug

### ISSUE THREAD

**Issue by AlligatorMods** [rdbo/ImGui-DirectX-9-Kiero-Hook#8]
I have not changed this code from yesterday, but today when i build the files, it gives two errors, one of which is `unresolved external symbol "public: __thiscall ImGui::ImGuiUserStyle::ImGuiUserStyle(void)" (??0ImGuiUserStyle@ImGui@@QAE@XZ) referenced int function "void __cdecl ImGui::'dynamic initializer for 'UserStyle(void)" (??_EUserStyle@ImGui@@YAXXZ` the error code is a LNK2019 Error, the second error is a LNK1120 linking back to the first (1 unresolved externals).

**Comment by AlligatorMods** [comment]
I would have posted this on stackoverflow, but its an error with the initial files of this project. imgui_tabs.cpp doesnt have definitions for some functions.

**Comment by rdbo** [comment]
Seems like some ImGui source files are not being compiled. Make sure all of them are included in the project.
